### ISSUE TITLE
Issue New Features : Add preset_mode icons

### ISSUE THREAD

**Issue by joffrey71** [piitaya/home-assistant-qubino-wire-pilot#14]
Hello,

I'm trying to add "icons.json" to your integration but it's not working.
What I'm doing :

1. I set "_attr_translation_key "
` _attr_translation_key = "qubino_climate"`

2. I added "icons.json"
```json
{
  "entity": {
    "climate": {
      "qubino_climate": {
        "state_attributes": {
          "preset_mode": {
            "state": {
              "comfort-1": "mdi:umbrella-beach",
              "comfort-2": "mdi:weather-night"
            }
          }
        }
      }
    }
  }
}
```

but no icons is displayed
![image](https://github.com/piitaya/home-assistant-qubino-wire-pilot/assets/23659848/6b2ab3b3-e644-450a-999b-84c6b52c039c)

How Can I achieve it ?

**Comment by piitaya** [comment]
I added icons in the latest update (`3.0.0`). I used generic icons to fit more users. Also, translations has been added 🙂

**Comment by joffrey71** [comment]
Hello @piitaya 

I updated integration but icons are not displayed.

![Image](https://github.com/user-attachments/assets/e41f36f9-9070-4ab2-8048-c08efc6078c9)

Did I miss something ?

**Comment by piitaya** [comment]
I would say it's a cache issue. You should have it.

**Comment by joffrey71** [comment]
Weird, I cleaned cache but it was NOK. 

I added a new qubino through UI and it's work. 

My others qubino are setup via yamal file only. Maybe déclaré a new one thought UI did the trick.

**Comment by piitaya** [comment]
Oh right ! If you are using `yaml`, you will need to add a `unique_id` to have translations and icon support.

**Comment by joffrey71** [comment]
I've already set `unique_id` for each qubino climates : 
```
- platform: qubino_wire_pilot
  name : Radiateur bureau
  unique_id: qubino_climate_office_room
  heater: light.flush_pilot
  sensor: sensor.sonde_bureau_temperature
  additional_modes: true

- platform: qubino_wire_pilot
  name: Radiateur Maé
  unique_id: qubino_climate_mae_bedroom
  heater: light.flush_pilot_3
  sensor: sensor.sonde_chambre_mae_temperature
  additional_modes: true

- platform: qubino_wire_pilot
  name: Radiateur chambre amis
  unique_id: qubino_climate_friends_bedroom
  heater: light.chauffage_amis
  sensor: sensor.sonde_chambre_amis_temperature
  additional_modes: true

- platform: qubino_wire_pilot
  name: Radiateur chambre parentale
  unique_id: qubino_climate_parents_bedroom
  heater: light.flush_pilot_2
  sensor: sensor.sonde_chambre_parentale_temperature
  additional_modes: true

- platform: qubino_wire_pilot
  name: Plancher chauffant salon
  unique_id: qubino_climate_living_room
  heater: light.chauffage_sejour
  sensor: sensor.sonde_salon_temperature
  additional_modes: true
```

But like I said, after adding a new one thought UI, yaml ones display icon and translation. 

Thanks for your work.
