### ISSUE TITLE
Climate Entities no longer exposed after 3.0 update

### ISSUE THREAD

**Issue by brunoloison** [piitaya/home-assistant-qubino-wire-pilot#16]
Hi, 
Thank u very very very very much for this wonderful Component that I've been so happy to discover (I come from Jeedom...and I've been afraid to see my heater were just.... lights).
All was working perfectly before 3.0 update. I haven't seen any post with this issue, so I decided to write it here.

Here is my climates in automation.yaml
![image](https://github.com/piitaya/home-assistant-qubino-wire-pilot/assets/26298935/79833ae2-8537-468b-aba7-d5d96fdcfff8)

and here is the results in the Entities 
![image](https://github.com/piitaya/home-assistant-qubino-wire-pilot/assets/26298935/00c9bf78-c19d-4afd-849b-53028d5f1170)

As a consequence, all my heaters are KO...
![image](https://github.com/piitaya/home-assistant-qubino-wire-pilot/assets/26298935/c97272cc-b7cb-4459-90d3-4261f30de321)

Have I missed anything??

Thx a lot
Bruno

**Comment by piitaya** [comment]
Do you have any error in the logs? https://my.home-assistant.io/redirect/logs/?provider=core

**Comment by piitaya** [comment]
I can reproduce it! It's because the case without sensor is not nicely handled. I will push a fix.

**Comment by brunoloison** [comment]
Thank you !!!!

Here is a copy of an error :

Enregistreur: homeassistant.components.climate
Source: helpers/entity_platform.py:598
intégration: Thermostat (documentation, problèmes)
S'est produit pour la première fois: 16:22:56 (8 occurrences)
Dernier enregistrement: 16:22:56

Error adding entity climate.thermostat_4 for domain climate with platform qubino_wire_pilot
Error adding entity climate.thermostat_5 for domain climate with platform qubino_wire_pilot
Error adding entity climate.thermostat_6 for domain climate with platform qubino_wire_pilot
Error adding entity climate.thermostat_7 for domain climate with platform qubino_wire_pilot
Error adding entity climate.thermostat_8 for domain climate with platform qubino_wire_pilot
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 598, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 912, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1361, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/qubino_wire_pilot/climate.py", line 189, in async_added_to_hass
    async_track_state_change_event(
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 326, in async_track_state_change_event
    if not (entity_ids := _async_string_to_lower_list(entity_ids)):
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 697, in _async_string_to_lower_list
    return [mstr.lower() for mstr in instr]
            ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by piitaya** [comment]
Can you try with the 3.0.1 version? It should be fixed.
