### ISSUE TITLE
Dimmer is now defined as 2 simple switches with the new zwave JS addon

### ISSUE THREAD

**Issue by argonaute199** [piitaya/home-assistant-qubino-wire-pilot#2]
Hello,
The ZwaveJS addon just changed and the dimmer is not anymore defined as a light with brightness but only as 2 simple switches. So your integration should not work anymore with the new zwave js version.

**Comment by piitaya** [comment]
I think it is an issue with the ZwaveJS addon or a node interview issue. The modes are always defined with the multi level switch between 0 and 99 (https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/devices/0x0159/zmnhjd.json) and it is converted to a light in home assistant.
