### ISSUE TITLE
class 'custom_components.qubino_wire_pilot.climate.QubinoWirePilotClimate'

### ISSUE THREAD

**Issue by c7274864** [piitaya/home-assistant-qubino-wire-pilot#7]
Good morning

Warning displayed
After installing the new version: 2.0.1

`Détails du journal (AVERTISSEMENT)
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:702
First occurred: 17:40:47 (4 occurrences)
Last logged: 17:40:48

Entity climate.radiateur_chambre (<class 'custom_components.qubino_wire_pilot.climate.QubinoWirePilotClimate'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please create a bug report at https://github.com/piitaya/home-assistant-qubino-wire-pilot/issues
Entity climate.radiateur_salon (<class 'custom_components.qubino_wire_pilot.climate.QubinoWirePilotClimate'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please create a bug report at https://github.com/piitaya/home-assistant-qubino-wire-pilot/issues
Entity climate.radiateur_cuisine (<class 'custom_components.qubino_wire_pilot.climate.QubinoWirePilotClimate'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please create a bug report at https://github.com/piitaya/home-assistant-qubino-wire-pilot/issues
Entity climate.radiateur_sdb (<class 'custom_components.qubino_wire_pilot.climate.QubinoWirePilotClimate'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please create a bug report at https://github.com/piitaya/home-assistant-qubino-wire-pilot/issues`

**Comment by piitaya** [comment]
Thank you for reporting. Fixed in 2.0.4.
