### ISSUE TITLE
Unable to update from temperature sensor: could not convert string to float: 'unknown'

### ISSUE THREAD

**Issue by c7274864** [piitaya/home-assistant-qubino-wire-pilot#8]
Good morning

Error displayed
After installing the new version: 2.0.1

`Cette erreur provient d'une intégration personnalisée
Logger: custom_components.qubino_wire_pilot.climate
Source: custom_components/qubino_wire_pilot/climate.py:245
Integration: qubino_wire_pilot ([documentation](https://github.com/piitaya/home-assistant-qubino-wire-pilot), [issues](https://github.com/piitaya/home-assistant-qubino-wire-pilot/issues))
First occurred: 17:40:50 (4 occurrences)
Last logged: 17:40:50

Unable to update from temperature sensor: could not convert string to float: 'unknown'`

**Comment by trollix** [comment]
Heelo,
the same error for me.

![screenshot_1555](https://github.com/piitaya/home-assistant-qubino-wire-pilot/assets/3890545/7b246254-756b-458f-beef-4c15353758b3)
